### ISSUE TITLE
AWS jobs not testing aliased changes

### ISSUE THREAD

**Issue by jillr** [ansible/ansible-zuul-jobs#1084]
Visible in this test PR.  

Testing with https://github.com/ansible-collections/community.aws/pull/700 with aws_config_rule as the only change no tests were run.
https://f7d8ed960619cc8d3749-b7d7790083b1c99ed8702216bc5cc6fc.ssl.cf1.rackcdn.com/700/14c86de5a5302cc9fa000d0d1940c0feda399ac1/check/ansible-test-splitter/4ffcef6/job-output.txt

https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/project-templates.yaml#L108 should have the effect of testing only modules which have changed modules or tests.

It happens this is an alias in aws_config.  I added a change to a non-aliased file (aws_region_info) and only aws_config_rule is identified by the test splitter.
https://f7d8ed960619cc8d3749-b7d7790083b1c99ed8702216bc5cc6fc.ssl.cf1.rackcdn.com/700/14c86de5a5302cc9fa000d0d1940c0feda399ac1/check/ansible-test-splitter/4ffcef6/job-output.txt

I'd venture a guess it's something in roles/ansible-test-splitter/files/test_changed.py?

**Comment by alinabuzachis** [comment]
@jillr @goneri  I tested the ansible-collections/community.aws#700 PR locally and ran `ansible-test-splitter/files/list_changed_targets.py` to check whether it returns the correct list of targets, and it seems working properly. The integration tests for `aws_region_info` are ran https://dashboard.zuul.ansible.com/t/ansible/build/d639ac62881c44a4856ef4e01414d7a0/log/job-output.txt, while the ones for `aws_config` aren't run because they are marked as Unsupported.

**Comment by jillr** [comment]
@alinabuzachis Looks like gravesm got this working but because we have way too many ticketing systems the Jira issue (ACA-257)) was closed but not the GH bug.
